name: StaffSpectate
version: '${project.version}'
main: com.arr4nn.staffspectate.StaffSpectate
api-version: 1.15
description: Let Staff spectate players without loosing their progress.
commands:
  ss:
    description: Spectate a player
    aliases:
      - staffspectate
      - spectate
      - sspectate
      - spec
    permission: staffspectate.use
  sspov:
    description: Spectate a player
    aliases:
      - spectatepov
      - specpov
    permission: staffspectate.use
  ssadmin:
    description: Admin managment of the plugin
    aliases:
      - staffspectateadmin
      - spectateadmin
      - sspectateadmin
    permission: staffspectate.admin

permissions:
  staffspectate.use:
    description: "Use the spectate command"
    children:
      - staffspectate.povspectate
      - staffspectate.spectate
      - staffspectate.leave
  staffspectate.admin:
    description: "Al the admin permissions"
    children:
      - staffspectate.notify
      - staffspectate.leavebypass

  staffspectate.spectate:
    description: "Start spectating a player"
  staffspectate.povspectate:
    description: "Start POV spectating a player"
  staffspectate.leave:
    description: "Leave spectator mode."

  staffspectate.notify:
    description: "Receive update messages"
  staffspectate.leavebypass:
    description: "Ability to exit spectator at the current location."