name: StaffSpectate
version: '${project.version}'
main: com.arr4nn.staffspectate.StaffSpectate
api-version: 1.15
description: Let Staff spectate players without loosing their progress.
commands:
  ss:
    description: Spectate a player
    aliases:
      - staffspectate
      - spectate
      - sspectate
    permission: staffspectate.use
  ssadmin:
    description: Admin managment of the plugin
    aliases:
      - staffspectateadmin
      - spectateadmin
      - sspectateadmin
    permission: staffspectate.admin